/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tumieproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author faith
 */
public class foodMenu extends javax.swing.JFrame {

    /**
     * Creates new form foodMenu
     */
    public foodMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jCheckBoxTwo = new javax.swing.JCheckBox();
        jCheckBoxOne = new javax.swing.JCheckBox();
        jCheckBoxThree = new javax.swing.JCheckBox();
        jCheckBoxFour = new javax.swing.JCheckBox();
        jCheckBoxFive = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jCheckBoxSix = new javax.swing.JCheckBox();
        jCheckBoxEight = new javax.swing.JCheckBox();
        jCheckBoxSeven = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("food menu");

        jPanel2.setBackground(new java.awt.Color(255, 102, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Chicken food");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\faith\\Desktop\\Pictures\\OIP2.jpg")); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\faith\\Desktop\\Pictures\\OIP3.jpg")); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\faith\\Desktop\\Pictures\\nuggets2.jpg")); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\faith\\Desktop\\Pictures\\OIP6.jpg")); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\faith\\Desktop\\Pictures\\z.jpg")); // NOI18N

        jCheckBoxTwo.setBackground(new java.awt.Color(255, 102, 51));
        jCheckBoxTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTwoActionPerformed(evt);
            }
        });

        jCheckBoxOne.setBackground(new java.awt.Color(255, 102, 51));
        jCheckBoxOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxOneActionPerformed(evt);
            }
        });

        jCheckBoxThree.setBackground(new java.awt.Color(255, 102, 51));
        jCheckBoxThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxThreeActionPerformed(evt);
            }
        });

        jCheckBoxFour.setBackground(new java.awt.Color(255, 102, 51));
        jCheckBoxFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFourActionPerformed(evt);
            }
        });

        jCheckBoxFive.setBackground(new java.awt.Color(255, 102, 51));
        jCheckBoxFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFiveActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 102, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton3.setBackground(new java.awt.Color(255, 153, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setText("click to comfirm order");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("By clicking you confirm the selected");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("customer name");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel4)
                .addGap(132, 132, 132)
                .addComponent(jLabel3)
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxOne)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBoxFour)))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxFive))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxTwo))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxThree)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(58, 58, 58))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxOne, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jCheckBoxThree, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLabel17))
                    .addComponent(jCheckBoxFive, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxFour, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        jPanel3.setBackground(new java.awt.Color(255, 102, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setText("Beef food");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\faith\\Desktop\\Pictures\\thh.jpg")); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\faith\\Desktop\\Pictures\\zz.jpg")); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\faith\\Desktop\\Pictures\\beef.jpg")); // NOI18N

        jCheckBoxSix.setBackground(new java.awt.Color(255, 102, 51));
        jCheckBoxSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSixActionPerformed(evt);
            }
        });

        jCheckBoxEight.setBackground(new java.awt.Color(255, 102, 51));
        jCheckBoxEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEightActionPerformed(evt);
            }
        });

        jCheckBoxSeven.setBackground(new java.awt.Color(255, 102, 51));
        jCheckBoxSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSevenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(133, 133, 133))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jCheckBoxSix))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxEight)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxSeven)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBoxSix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jCheckBoxSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxEight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(49, 49, 49))
        );

        jPanel4.setBackground(new java.awt.Color(255, 102, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel16.setText("Your order Receipt");

        jTextArea1.setBackground(new java.awt.Color(255, 153, 102));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton2.setBackground(new java.awt.Color(255, 102, 51));
        jButton2.setText("logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 64, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel16)
                .addGap(75, 75, 75)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(847, 847, 847))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTwoActionPerformed

    private void jCheckBoxOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxOneActionPerformed

    private void jCheckBoxThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxThreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxThreeActionPerformed

    private void jCheckBoxFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxFourActionPerformed

    private void jCheckBoxFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxFiveActionPerformed

    private void jCheckBoxSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxSixActionPerformed

    private void jCheckBoxEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxEightActionPerformed

    private void jCheckBoxSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSevenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxSevenActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //query to the databse
        String url ="jdbc:derby://localhost:1527/foodstuff";
        String user= "ROOT";
        String pass = "ROOT";

        String sql = "INSERT INTO ORDERFOOD (NAME,FIRST_ORDER,SECOND_ORDER,LAST_ORDER) VALUES(?,?,?,?)";

        //customer name
        String name = jTextField1.getText();

        //checking if the name field is empty
        if(name.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "The customer name is required");
        }
        else
        {
            try {
                //making a connection to the database
                Connection con = DriverManager.getConnection(url, user, pass);
                PreparedStatement pst = con.prepareStatement(sql);

                if(jCheckBoxOne.isSelected() && jCheckBoxTwo.isSelected() && jCheckBoxThree.isSelected())
                {
                   //setting the details to the database column
                    pst.setString(1, name);
                    pst.setString(2, "spicy wings");
                    pst.setString(3, "hot wings");
                    pst.setString(4, "nuggets");

                    //executing the query
                    int num = pst.executeUpdate();

                    int price = 10 +20 + 15;
                    //checking f the query is successful
                    if(num>0)
                    {
                        JOptionPane.showMessageDialog(null, "The request was successful");
                        //outputing to the text area
                        jTextArea1.setText("YOUR ORDER REQUEST \n"+
                                "          "+
                                "please do confirm the details below for issue \n \n"+
                                "    "+"CLIENT_NAME :"+name+"\n"+
                                "    "+"CLIENT_ORDER1 : spicy wings\n"+
                                "    "+"CLIENT_ORDER2 : hot wings \n"+
                                "    "+"CLIENT_ORDER3 : nuggets\n"+
                                "      PRICE : \n"+price+".00"+
                                "     THANK YOU FOR SHOPPING WITH US \n" 
                        );
                    }
                }
                else if(jCheckBoxOne.isSelected() && jCheckBoxTwo.isSelected() && jCheckBoxFour.isSelected())
                {
                    //setting the details to the database column
                    pst.setString(1, name);
                    pst.setString(2, "spicy wings");
                    pst.setString(3, "hot wings");
                    pst.setString(4, "sliced chicken");

                    //executing the query
                    int num = pst.executeUpdate();

                    int price = 10 +20 + 35;
                    //checking f the query is successful
                    if(num>0)
                    {
                        JOptionPane.showMessageDialog(null, "The request was successful");
                        //outputing to the text area
                        jTextArea1.setText("YOUR ORDER REQUEST \n"+
                                "          "+
                                "please do confirm the details below for issue \n \n"+
                                "    "+"CLIENT_NAME :"+name+"\n"+
                                "    "+"CLIENT_ORDER1 : spicy wings\n"+
                                "    "+"CLIENT_ORDER2 : hot wings \n"+
                                "    "+"CLIENT_ORDER3 : sliced chicken\n"+
                                "      PRICE : \n"+price+".00"+
                                "     THANK YOU FOR SHOPPING WITH US \n" 
                        );
                    }
                }
                else if(jCheckBoxOne.isSelected() && jCheckBoxTwo.isSelected() && jCheckBoxFive.isSelected())
                {
                    //setting the details to the database column
                    pst.setString(1, name);
                    pst.setString(2, "spicy wings");
                    pst.setString(3, "hot wings");
                    pst.setString(4, "quoted drum stick");

                    //executing the query
                    int num = pst.executeUpdate();

                    int price = 10 +20 + 30;
                    //checking f the query is successful
                    if(num>0)
                    {
                        JOptionPane.showMessageDialog(null, "The request was successful");
                        //outputing to the text area
                        jTextArea1.setText("YOUR ORDER REQUEST \n"+
                                "          "+
                                "please do confirm the details below for issue \n \n"+
                                "   "+"CLIENT_NAME :"+name+"\n"+
                                "   "+"CLIENT_ORDER1 : spicy wings\n"+
                                "   "+"CLIENT_ORDER2 : hot wings \n"+
                                "   "+"CLIENT_ORDER3 : quoted drum stick\n"+
                                "      PRICE : \n"+price+".00"+
                                "     THANK YOU FOR SHOPPING WITH US \n" 
                        );
                    }
                }
                else if(jCheckBoxOne.isSelected() && jCheckBoxThree.isSelected() && jCheckBoxFour.isSelected())
                {
                    //setting the details to the database column
                    pst.setString(1, name);
                    pst.setString(2, "spicy wings");
                    pst.setString(3, "nuggets");
                    pst.setString(4, "sliced chicken");

                    //executing the query
                    int num = pst.executeUpdate();

                    int price = 10 +15 + 35;
                    //checking f the query is successful
                    if(num>0)
                    {
                        JOptionPane.showMessageDialog(null, "The request was successful");
                        //outputing to the text area
                        jTextArea1.setText("YOUR ORDER REQUEST \n"+
                                "          "+
                                "please do confirm the details below for issue \n \n"+
                                "    "+"CLIENT_NAME :"+name+"\n"+
                                "    "+"CLIENT_ORDER1 : spicy wings\n"+
                                "    "+"CLIENT_ORDER2 : nuggets \n"+
                                "    "+"CLIENT_ORDER3 : sliced chicken\n"+
                                "      PRICE : \n"+price+".00"+
                                "     THANK YOU FOR SHOPPING WITH US \n" 
                        );
                    }
                }
                else if(jCheckBoxOne.isSelected() && jCheckBoxThree.isSelected() && jCheckBoxFive.isSelected())
                {
                    //setting the details to the database column
                    pst.setString(1, name);
                    pst.setString(2, "spicy wings");
                    pst.setString(3, "nuggets");
                    pst.setString(4, "quoted drum stick");

                    //executing the query
                    int num = pst.executeUpdate();

                    int price = 10 +15 + 30;
                    //checking f the query is successful
                    if(num>0)
                    {
                        JOptionPane.showMessageDialog(null, "The request was successful");
                        //outputing to the text area
                        jTextArea1.setText("YOUR ORDER REQUEST \n"+
                                "          "+
                                "please do confirm the details below for issue \n \n"+
                                "    "+"CLIENT_NAME :"+name+"\n"+
                                "    "+"CLIENT_ORDER1 : spicy wings\n"+
                                "    "+"CLIENT_ORDER2 : nuggets \n"+
                                "    "+"CLIENT_ORDER3 : quoted drum stick\n"+
                                "      PRICE : \n"+price+".00"+
                                "     THANK YOU FOR SHOPPING WITH US \n" 
                        );
                    }
                }
                else if(jCheckBoxOne.isSelected() && jCheckBoxFour.isSelected() && jCheckBoxFive.isSelected())
                {
                    //setting the details to the database column
                    pst.setString(1, name);
                    pst.setString(2, "spicy wings");
                    pst.setString(3, "slied chicken");
                    pst.setString(4, "quoted drum stick");

                    //executing the query
                    int num = pst.executeUpdate();

                    int price = 10 +35 + 30;
                    //checking f the query is successful
                    if(num>0)
                    {
                        JOptionPane.showMessageDialog(null, "The request was successful");
                        //outputing to the text area
                        jTextArea1.setText("YOUR ORDER REQUEST \n"+
                                "          "+
                                "please do confirm the details below for issue \n \n"+
                                "    "+"CLIENT_NAME :"+name+"\n"+
                                "    "+"CLIENT_ORDER1 : spicy wings\n"+
                                "    "+"CLIENT_ORDER2 : nuggets \n"+
                                "     "+"CLIENT_ORDER3 : quoted drum stick\n"+
                                "      PRICE : \n"+price+".00"+
                                "     THANK YOU FOR SHOPPING WITH US \n" 
                        );
                    }

                }
                else if(jCheckBoxOne.isSelected() && jCheckBoxTwo.isSelected() && jCheckBoxSix.isSelected())
                {
                    //setting the details to the database column
                    pst.setString(1, name);
                    pst.setString(2, "spicy wings");
                    pst.setString(3, "hot wings");
                    pst.setString(4, "bruiscit");

                    //executing the query
                    int num = pst.executeUpdate();

                    int price = 10 +20 + 45;
                    //checking f the query is successful
                    if(num>0)
                    {
                        JOptionPane.showMessageDialog(null, "The request was successful");
                        //outputing to the text area
                        jTextArea1.setText("YOUR ORDER REQUEST \n"+
                                "          "+
                                "please do confirm the details below for issue \n \n"+
                                "    "+"CLIENT_NAME :"+name+"\n"+
                                "    "+"CLIENT_ORDER1 : spicy wings\n"+
                                "    "+"CLIENT_ORDER2 : hot wings \n"+
                                "    "+"CLIENT_ORDER3 : bruiscit\n"+
                                "      PRICE : \n"+price+".00"+
                                "     THANK YOU FOR SHOPPING WITH US \n" 
                        );
                    }

                }
                else if(jCheckBoxOne.isSelected() && jCheckBoxTwo.isSelected() && jCheckBoxSeven.isSelected())
                {
                    //setting the details to the database column
                    pst.setString(1, name);
                    pst.setString(2, "spicy wings");
                    pst.setString(3, "hot wings");
                    pst.setString(4, "braide meat");

                    //executing the query
                    int num = pst.executeUpdate();

                    int price = 10 +20 + 28;
                    //checking f the query is successful
                    if(num>0)
                    {
                        JOptionPane.showMessageDialog(null, "The request was successful");
                        //outputing to the text area
                        jTextArea1.setText("YOUR ORDER REQUEST \n"+
                                "          "+
                                "please do confirm the details below for issue \n \n"+
                                "   "+"CLIENT_NAME :"+name+"\n"+
                                "   "+"CLIENT_ORDER1 : spicy wings\n"+
                                "   "+"CLIENT_ORDER2 : hot wings \n"+
                                "   "+"CLIENT_ORDER3 : braide meat\n"+
                                "      PRICE : \n"+price+".00"+
                                "     THANK YOU FOR SHOPPING WITH US \n" 
                        );
                    }

                }
                else if(jCheckBoxOne.isSelected() && jCheckBoxTwo.isSelected() && jCheckBoxEight.isSelected())
                {
                    //setting the details to the database column
                    pst.setString(1, name);
                    pst.setString(2, "spicy wings");
                    pst.setString(3, "hot wings");
                    pst.setString(4, "meens salad");

                    //executing the query
                    int num = pst.executeUpdate();

                    int price = 10 +20 + 23;
                    //checking f the query is successful
                    if(num>0)
                    {
                        JOptionPane.showMessageDialog(null, "The request was successful");
                        //outputing to the text area
                        jTextArea1.setText("YOUR ORDER REQUEST \n"+
                                "          "+
                                "please do confirm the details below for issue \n \n"+
                                "     "+"CLIENT_NAME :"+name+"\n"+
                                "     "+"CLIENT_ORDER1 : spicy wings\n"+
                                "     "+"CLIENT_ORDER2 : hot wings \n"+
                                "     "+"CLIENT_ORDER3 : meens salad\n"+
                                "      PRICE : \n"+price+".00"+
                                "     THANK YOU FOR SHOPPING WITH US \n" 
                        );
                    }

                }
                else if(jCheckBoxOne.isSelected() && jCheckBoxThree.isSelected() && jCheckBoxSix.isSelected())
                {
                    //setting the details to the database column
                    pst.setString(1, name);
                    pst.setString(2, "spicy wings");
                    pst.setString(3, "nuggets");
                    pst.setString(4, "bruiscit");

                    //executing the query
                    int num = pst.executeUpdate();

                    int price = 10 +15 + 45;
                    //checking f the query is successful
                    if(num>0)
                    {
                        JOptionPane.showMessageDialog(null, "The request was successful");
                        //outputing to the text area
                        jTextArea1.setText("YOUR ORDER REQUEST \n"+
                                "          "+
                                "please do confirm the details below for issue \n \n"+
                                "      "+"CLIENT_NAME :"+name+"\n"+
                                "      "+"CLIENT_ORDER1 : spicy wings\n"+
                                "      "+"CLIENT_ORDER2 : hot wings \n"+
                                "      "+"CLIENT_ORDER3 : bruiscit\n"+
                                "      PRICE : \n"+price+".00"+
                                "     THANK YOU FOR SHOPPING WITH US \n" 
                        );
                    }

                }
                else if(jCheckBoxOne.isSelected() && jCheckBoxThree.isSelected() && jCheckBoxSeven.isSelected())
                {
                    //setting the details to the database column
                    pst.setString(1, name);
                    pst.setString(2, "spicy wings");
                    pst.setString(3, "nuggets");
                    pst.setString(4, "braid meat");

                    //executing the query
                    int num = pst.executeUpdate();

                    int price = 10 +15 + 28;
                    //checking f the query is successful
                    if(num>0)
                    {
                        JOptionPane.showMessageDialog(null, "The request was successful");
                        //outputing to the text area
                        jTextArea1.setText("YOUR ORDER REQUEST \n"+
                                "          "+
                                "please do confirm the details below for issue \n \n"+
                                "    "+"CLIENT_NAME :"+name+"\n"+
                                "    "+"CLIENT_ORDER1 : spicy wings\n"+
                                "    "+"CLIENT_ORDER2 : nuggets \n"+
                                "    "+"CLIENT_ORDER3 : braide meat\n"+
                                "      PRICE : \n"+price+".00"+
                                "     THANK YOU FOR SHOPPING WITH US \n" 
                        );
                    }

                }
                else if(jCheckBoxOne.isSelected() && jCheckBoxThree.isSelected() && jCheckBoxEight.isSelected())
                {
                    //setting the details to the database column
                    pst.setString(1, name);
                    pst.setString(2, "spicy wings");
                    pst.setString(3, "nuggets");
                    pst.setString(4, "meens salad");

                    //executing the query
                    int num = pst.executeUpdate();

                    int price = 10 +15 + 23;
                    //checking f the query is successful
                    if(num>0)
                    {
                        JOptionPane.showMessageDialog(null, "The request was successful");
                        //outputing to the text area
                        jTextArea1.setText("YOUR ORDER REQUEST \n"+
                                "          "+
                                "please do confirm the details below for issue \n \n"+
                                "     "+"CLIENT_NAME :"+name+"\n"+
                                "     "+"CLIENT_ORDER1 : spicy wings\n"+
                                "     "+"CLIENT_ORDER2 : hot wings \n"+
                                "     "+"CLIENT_ORDER3 : meens salad\n"+
                                "      PRICE : \n"+price+".00"+
                                "     THANK YOU FOR SHOPPING WITH US \n" 
                        );
                    }

                }
                else if(jCheckBoxOne.isSelected() && jCheckBoxFour.isSelected() && jCheckBoxSix.isSelected())
                {
                    //setting the details to the database column
                    pst.setString(1, name);
                    pst.setString(2, "spicy wings");
                    pst.setString(3, "sliced chicken");
                    pst.setString(4, "bruiscit");

                    //executing the query
                    int num = pst.executeUpdate();

                    int price = 10 +35 + 45;
                    //checking f the query is successful
                    if(num>0)
                    {
                        JOptionPane.showMessageDialog(null, "The request was successful");
                        //outputing to the text area
                        jTextArea1.setText("YOUR ORDER REQUEST \n"+
                                "          "+
                                "please do confirm the details below for issue \n \n"+
                                "     "+"CLIENT_NAME :"+name+"\n"+
                                "     "+"CLIENT_ORDER1 : spicy wings\n"+
                                "     "+"CLIENT_ORDER2 : hot wings \n"+
                                "     "+"CLIENT_ORDER3 : bruiscit\n"+
                                "      PRICE : \n"+price+".00"+
                                "     THANK YOU FOR SHOPPING WITH US \n" 
                        );
                    }

                }
                else if(jCheckBoxOne.isSelected() && jCheckBoxFour.isSelected() && jCheckBoxSeven.isSelected())
                {
                    //setting the details to the database column
                    pst.setString(1, name);
                    pst.setString(2, "spicy wings");
                    pst.setString(3, "sliced chicken");
                    pst.setString(4, "braide meat");

                    //executing the query
                    int num = pst.executeUpdate();

                    int price = 10 +35 + 28;
                    //checking f the query is successful
                    if(num>0)
                    {
                        JOptionPane.showMessageDialog(null, "The request was successful");
                        //outputing to the text area
                        jTextArea1.setText("YOUR ORDER REQUEST \n"+
                                "          "+
                                "please do confirm the details below for issue \n \n"+
                                "    "+"CLIENT_NAME :"+name+"\n"+
                                "    "+"CLIENT_ORDER1 : spicy wings\n"+
                                "    "+"CLIENT_ORDER2 : hot wings \n"+
                                "    "+"CLIENT_ORDER3 : braide meat\n"+
                                "      PRICE : \n"+price+".00"+
                                "     THANK YOU FOR SHOPPING WITH US \n" 
                        );
                    }

                }
                else if(jCheckBoxOne.isSelected() && jCheckBoxFour.isSelected() && jCheckBoxEight.isSelected())
                {
                    //setting the details to the database column
                    pst.setString(1, name);
                    pst.setString(2, "spicy wings");
                    pst.setString(3, "sliced chicken");
                    pst.setString(4, "meens salad");

                    //executing the query
                    int num = pst.executeUpdate();

                    int price = 10 +35 + 23;
                    //checking f the query is successful
                    if(num>0)
                    {
                        JOptionPane.showMessageDialog(null, "The request was successful");
                        //outputing to the text area
                        jTextArea1.setText("YOUR ORDER REQUEST \n"+
                                "          "+
                                "please do confirm the details below for issue \n \n"+
                                "    "+"CLIENT_NAME :"+name+"\n"+
                                "    "+"CLIENT_ORDER1 : spicy wings\n"+
                                "    "+"CLIENT_ORDER2 : hot wings \n"+
                                "    "+"CLIENT_ORDER3 : meens salad\n"+
                                "      PRICE : \n"+price+".00"+
                                "     THANK YOU FOR SHOPPING WITH US \n" 
                        );
                    }

                }
                else if(jCheckBoxOne.isSelected() && jCheckBoxFive.isSelected() && jCheckBoxSix.isSelected())
                {
                    //setting the details to the database column
                    pst.setString(1, name);
                    pst.setString(2, "spicy wings");
                    pst.setString(3, "drum stick");
                    pst.setString(4, "bruiscit");

                    //executing the query
                    int num = pst.executeUpdate();

                    int price = 10 +30 + 45;
                    //checking f the query is successful
                    if(num>0)
                    {
                        JOptionPane.showMessageDialog(null, "The request was successful");
                        //outputing to the text area
                        jTextArea1.setText("YOUR ORDER REQUEST \n"+
                                "          "+
                                "please do confirm the details below for issue \n \n"+
                                "    "+"CLIENT_NAME :"+name+"\n"+
                                "    "+"CLIENT_ORDER1 : spicy wings\n"+
                                "    "+"CLIENT_ORDER2 : drum stick \n"+
                                "    "+"CLIENT_ORDER3 : bruiscit\n"+
                                "      PRICE : \n"+price+".00"+
                                "     THANK YOU FOR SHOPPING WITH US \n" 
                        );
                    }

                }
                else if(jCheckBoxOne.isSelected() && jCheckBoxFive.isSelected() && jCheckBoxSeven.isSelected())
                {
                    //setting the details to the database column
                    pst.setString(1, name);
                    pst.setString(2, "spicy wings");
                    pst.setString(3, "drum stick");
                    pst.setString(4, "braide meat");

                    //executing the query
                    int num = pst.executeUpdate();

                    int price = 10 +30 + 28;
                    //checking f the query is successful
                    if(num>0)
                    {
                        JOptionPane.showMessageDialog(null, "The request was successful");
                        //outputing to the text area
                        jTextArea1.setText("YOUR ORDER REQUEST \n"+
                                "          "+
                                "please do confirm the details below for issue \n \n"+
                                "   "+"CLIENT_NAME :"+name+"\n"+
                                "   "+"CLIENT_ORDER1 : spicy wings\n"+
                                "   "+"CLIENT_ORDER2 : drum stick \n"+
                                "   "+"CLIENT_ORDER3 : braide meat\n"+
                                "      PRICE : \n"+price+".00"+
                                "     THANK YOU FOR SHOPPING WITH US \n" 
                        );
                    }

                }
                else if(jCheckBoxOne.isSelected() && jCheckBoxFive.isSelected() && jCheckBoxEight.isSelected())
                {
                    //setting the details to the database column
                    pst.setString(1, name);
                    pst.setString(2, "spicy wings");
                    pst.setString(3, "drum stick");
                    pst.setString(4, "meens salad");

                    //executing the query
                    int num = pst.executeUpdate();

                    int price = 10 +30 + 23;
                    //checking f the query is successful
                    if(num>0)
                    {
                        JOptionPane.showMessageDialog(null, "The request was successful");
                        //outputing to the text area
                        jTextArea1.setText("YOUR ORDER REQUEST \n"+
                                "          "+
                                "please do confirm the details below for issue \n \n"+
                                "   "+"CLIENT_NAME :"+name+"\n"+
                                "   "+"CLIENT_ORDER1 : spicy wings\n"+
                                "   "+"CLIENT_ORDER2 : drum stick \n"+
                                "   "+"CLIENT_ORDER3 : meens salad\n"+
                                "      PRICE : \n"+price+".00"+
                                "     THANK YOU FOR SHOPPING WITH US \n" 
                        );
                    }

                }
                else if(jCheckBoxOne.isSelected() && jCheckBoxSix.isSelected() && jCheckBoxSeven.isSelected())
                {
                    //setting the details to the database column
                    pst.setString(1, name);
                    pst.setString(2, "spicy wings");
                    pst.setString(3, "bruiscit");
                    pst.setString(4, "braide meat");

                    //executing the query
                    int num = pst.executeUpdate();

                    int price = 10 +30 + 28;
                    //checking f the query is successful
                    if(num>0)
                    {
                        JOptionPane.showMessageDialog(null, "The request was successful");
                        //outputing to the text area
                        jTextArea1.setText("YOUR ORDER REQUEST \n"+
                                "          "+
                                "please do confirm the details below for issue \n \n"+
                                "    "+"CLIENT_NAME :"+name+"\n"+
                                "    "+"CLIENT_ORDER1 : spicy wings\n"+
                                "    "+"CLIENT_ORDER2 : drum stick \n"+
                                "    "+"CLIENT_ORDER3 : braide meat\n"+
                                "      PRICE : \n"+price+".00"+
                                "     THANK YOU FOR SHOPPING WITH US \n" 
                        );
                    }

                }
                else if(jCheckBoxOne.isSelected() && jCheckBoxSix.isSelected() && jCheckBoxEight.isSelected())
                {
                    //setting the details to the database column
                    pst.setString(1, name);
                    pst.setString(2, "spicy wings");
                    pst.setString(3, "bruiscit");
                    pst.setString(4, "meens salad");

                    //executing the query
                    int num = pst.executeUpdate();

                    int price = 10 +30 + 23;
                    //checking f the query is successful
                    if(num>0)
                    {
                        JOptionPane.showMessageDialog(null, "The request was successful");
                        //outputing to the text area
                        jTextArea1.setText("YOUR ORDER REQUEST \n"+
                                "          "+
                                "please do confirm the details below for issue \n \n"+
                                "   "+"CLIENT_NAME :"+name+"\n"+
                                "   "+"CLIENT_ORDER1 : spicy wings\n"+
                                "   "+"CLIENT_ORDER2 : drum stick \n"+
                                "   "+"CLIENT_ORDER3 : meens salad\n"+
                                "      PRICE : \n"+price+".00"+
                                "     THANK YOU FOR SHOPPING WITH US \n" 
                        );
                    }

                }
                else if(jCheckBoxOne.isSelected() && jCheckBoxSeven.isSelected() && jCheckBoxEight.isSelected())
                {
                    //setting the details to the database column
                    pst.setString(1, name);
                    pst.setString(2, "spicy wings");
                    pst.setString(3, "braid meat");
                    pst.setString(4, "meens salad");

                    //executing the query
                    int num = pst.executeUpdate();

                    int price = 10 +28 + 23;
                    //checking f the query is successful
                    if(num>0)
                    {
                        JOptionPane.showMessageDialog(null, "The request was successful");
                        //outputing to the text area
                        jTextArea1.setText("YOUR ORDER REQUEST \n"+
                                "          "+
                                "please do confirm the details below for issue \n \n"+
                                "   "+"CLIENT_NAME :"+name+"\n"+
                                "   "+"CLIENT_ORDER1 : spicy wings\n"+
                                "   "+"CLIENT_ORDER2 : braide meat \n"+
                                "   "+"CLIENT_ORDER3 : meens salad\n"+
                                "      PRICE : \n"+price+".00"+
                                "     THANK YOU FOR SHOPPING WITH US \n" 
                        );
                    }
                }
            }
            catch(SQLIntegrityConstraintViolationException e)
                {
                    JOptionPane.showMessageDialog(null, "The id and the book title should be unique, \n      THANK YOU");
                }
            catch(NumberFormatException e)
            {
                JOptionPane.showMessageDialog(null,"you might have entered string in a number field \n"
                        + "Renter the details again, THANK YOU");
            }
            catch (SQLException ex) {
                Logger.getLogger(foodMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //
        login log = new login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(foodMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(foodMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(foodMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(foodMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new foodMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBoxEight;
    private javax.swing.JCheckBox jCheckBoxFive;
    private javax.swing.JCheckBox jCheckBoxFour;
    private javax.swing.JCheckBox jCheckBoxOne;
    private javax.swing.JCheckBox jCheckBoxSeven;
    private javax.swing.JCheckBox jCheckBoxSix;
    private javax.swing.JCheckBox jCheckBoxThree;
    private javax.swing.JCheckBox jCheckBoxTwo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
